# Generated by Django 5.1.3 on 2024-11-22 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('backgroundImage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=100)),
                ('RoomId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='CreatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user'),
        ),
    ]
